purbeurre/aliments_off/urls.py
"""Docstring"""
from django.urls import path
from . import views

app_name = 'aliments_off'
urlpatterns = [
    path('search/', views.SearchView.as_view(), name='search'),
    path('<int:product_id>/result/', views.ResultView.as_view(), name='result'),
    path('<int:pk>/detail/', views.DetailProductView.as_view(), name='detail'),
    path('save/', views.SaveView, name='save'),
    path('myproducts/', views.MyProductsView.as_view(), name='myproducts'),
]

purbeurre/homepage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='homepage'),
    path('mentions-legales', views.mentions, name='mentions'),
]

purbeurre/purbeurre/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('aliments_off.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('homepage.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purbeurre/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    
]

purbeurre/aliments_off/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.

class Products(models.Model):
    id_product = models.IntegerField()
    product_name = models.CharField(max_length=200)
    nutritional_score = models.CharField(max_length=2)
    url = models.URLField()
    category_name = models.CharField(max_length=200)
    img_url = models.URLField()
    fat = models.CharField(max_length=8, null=True)
    fat_100g = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    saturated_fat = models.CharField(max_length=8, null=True)
    saturated_fat_100g = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    sugars = models.CharField(max_length=8, null=True)
    sugars_100g = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    salt = models.CharField(max_length=8, null=True)
    salt_100g = models.DecimalField(max_digits=3, decimal_places=1, null=True)

    def __str__(self):
        return self.product_name

class SaveProducts(models.Model):
    id_product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

purbeurre/homepage/models.py
from django.db import models


# Create your models here.

purbeurre/users/models.py
from django.db import models

# Create your models here.

purbeurre/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

purbeurre/aliments_off/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, DeleteView, RedirectView

from django.contrib.auth.models import User
from .models import Products, SaveProducts


class SearchView(ListView):
    """Return products from DB from query."""
    template_name = 'aliments_off/search.html'
    paginate_by = 9

    def get_queryset(self):
        return Products.objects.filter(
            product_name__icontains=self.request.GET['query']).\
                order_by('product_name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.request.GET['query']
        context['target'] = 'aliments_off:result'
        return context


class ResultView(ListView):
    """Return substitutes with same category and better/equal nutrigrade."""
    template_name = 'aliments_off/result.html'

    def get_queryset(self):
        self.product = Products.objects.get(pk=self.kwargs['product_id'])
        return Products.objects\
            .filter(category_name=self.product.category_name)\
            .filter(nutritional_score__lte=self.product.nutritional_score)\
            .exclude(id=self.kwargs['product_id'])\
            .order_by('nutritional_score')[:9]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'allreadysaved' in self.request.GET:
            context['message'] = 'Déjà enregistré'
        context['query'] = self.product.product_name
        context['product'] = self.product
        context['title'] = self.product
        context['target'] = 'aliments_off:detail'
        return context


class DetailProductView(DetailView):
    """Show product details."""
    template_name = 'aliments_off/detail.html'
    model = Products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = kwargs['object'].product_name
        return context


@login_required
def SaveView(request):
    """Save product/substitute."""
    if request.method == 'POST':
        # get data from POST
        id_product = request.POST['id_product_sub']
        next_url = request.POST['next']
        # get data from DB
        product_obj = Products.objects.get(pk=id_product)
        user_obj = User.objects.get(pk=request.user.id)
        # test if all obj are sets
        if product_obj and user_obj:
            # create Substitute or return "allreadysaved"
            obj, created = SaveProducts.objects.get_or_create(
                user_id=user_obj,
                id_product=product_obj,
                )
            if created:
                return redirect('aliments_off:myproducts')
            else:
                return redirect(next_url+"?allreadysaved")
    return redirect('homepage')


class MyProductsView(LoginRequiredMixin, ListView):
    """Show saved products."""
    template_name = 'aliments_off/my_products.html'
    paginate_by = 4

    def get_queryset(self):
        return SaveProducts.objects.filter(
            user_id=self.request.user.id).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mes produits'
        context['target'] = 'aliments_off:result'
        return context

purbeurre/homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def home(request):
    return render(request, 'homepage/home.html')


def mentions(request):
    return render(request, 'homepage/mentions-legales.html')

purbeurre/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'hey {username}! c\'est bon tu peux te connecter !')
            return redirect('login')

    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    
    return render(request, 'users/profile.html')

purbeurre/aliments_off/templates/aliments_off/base_product_title_img.html
 <!-- Product Search Section -->
    <header id="product-search" class="bg-product-search">
        <div class="container-fluid h-200">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <!-- <img src="{#product.image_url#}" alt=""> -->
            <h1 class="text-white font-weight-bold">{{ query|title }}</h1>
        </div>
        </div>
    </header>
    
    <!-- Modify product picture -->
    <style>
    .bg-product-search {
        padding-top: 10rem;
        background-color: #345A61;
        background: linear-gradient(to bottom,rgba(92,77,66,.8) 0,rgba(92,77,66,.8) 100%),
            url({{products.img_url}});
        background-repeat: no-repeat;
        background-position-x: 35%;
        background-position-y: 50%;
    }
    </style>

purbeurre/aliments_off/templates/aliments_off/detail.html
{% extends "base.html" %}

{% load static %}

{% block body %}

{% include 'aliments_off/base_product_title_img.html' %}

  <!-- Product Details -->
  <section id="product-detail">
    <div class="container">
      <div class="row align-items-center justify-content-center py-3 mx-1">
        <div class="col-12 col-lg-6 text-center">
          <img src="{% static 'img/codenutri/nutriscore-'|add:products.nutritional_score|add:'.svg' %}" alt="">
        </div>
        <div class="col-12 col-lg-6">
          <h3>Repères nutritionnels pour 100 g</h3>
          <ul class="nutrient-levels">
            <li class="{{ products.fat }}">{{ products.fat_100g }} g Matières grasses / Lipides</li>
            <li class="{{ products.saturated_fat }}">{{ products.saturated_fat_100g }} g Acides gras saturés</li>
            <li class="{{ products.sugars }}">{{ products.sugars_100g }} g Sucres</li>
            <li class="{{ products.salt }}">{{ products.salt_100g }} g Sel</li>
          </ul>
        </div>
        <div class="col-12 text-center">
          <a href="{{products.url}}" target="_blank">
            <button type="button" class="btn btn-lg btn-outline-secondary">Voir la fiche Openfoodfacts</button>
          </a>
        </div>
        <div class="col-12 text-center">
          <button onclick="window.history.back();" type="button" class="btn btn-lg btn-outline-secondary mt-0">Retour</button>
        </div>
      </div>
    </div>
  </section>

{% endblock body %}

purbeurre/aliments_off/templates/aliments_off/my_products.html
{% extends "base.html" %}

{% load static %}

{% block body %}

{% include 'base_title_section.html' %}
  
  <!-- My Product Result Section -->
  <section id="product-result">
    <div class="container">
        {% if not object_list %}
        <div class="row align-items-center justify-content-center"></div>
          <div class="alert alert-warning">Il n'y a pas de produits enregistrés</div>
        </div>
        {% endif %}
      <div class="row align-items-center justify-content-center">
        {% for sl in object_list %}
          <div class="col-4 mx-1 px-0">
            <div class="product-thumb-my_product">
              <div class="nutriscore nutriscore-{{sl.id_product.nutritional_score|upper}} text-center"></div>
              <a href="{% url 'aliments_off:detail' sl.id_product.id %}">
                <img src="{{sl.id_product.img_url}}" class="rounded mx-auto d-block" alt="">
              </a>
              <div class="product-thumb-legend">
                <p class="text-center">{{sl.id_product|title}}</p>
              </div>
            </div>
          </div>
        {% endfor %}
        {% if is_paginated %}
        <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="pagination text-center">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="?page={{ page_obj.previous_page_number }}">Précédente</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="?page={{ page_obj.next_page_number }}">Suivante</a>
                  {% endif %}
              </span>
          </div>
        </div>
        {% endif %}
    </div>
    </div>
    </section>

{% endblock body %}

purbeurre/aliments_off/templates/aliments_off/result.html
{% extends "base.html" %}

{% load static %}

{% block body %}

{% include 'aliments_off/base_product_title_img.html' %}
  
  <!-- Product Result Section -->
  <section id="product-result">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-12 text-center">
          <h2>Vous pouvez remplacer cet aliment par : </h2>
          {% if message %}
            <div class="alert alert-warning">{{message}}</div>
          {% endif %}
        </div>
        {% for substitute in object_list %}
          <div class="col-11 col-lg-4">
            <div class="product-thumb">
              <div class="nutriscore nutriscore-{{substitute.nutritional_score|upper}} text-center"></div>
                <a href="{% url target substitute.id %}">
                  <img src="{{substitute.img_url}}" class="rounded mx-auto d-block" alt="">
                </a>
              <div class="product-thumb-legend">
                <div class="text-center">{{substitute|title}}</div>
                <div class="text-center">
                  <form action="{% url 'aliments_off:save' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <input type="hidden" name="id_product_sub" value="{{ substitute.id }}">
                    <button type="submit" class="btn btn-link"><i class="fas fa-save fa-1x"></i> Sauvegarder</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
</section>

{% endblock body %}

purbeurre/aliments_off/templates/aliments_off/search.html
{% extends "base.html" %}

{% load static %}

{% block body %}

{% include 'base_title_section.html' %}

  <!-- Product Result Section -->
  <section id="product-result">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-12 text-center">
          <h2>Choisissez votre produit actuel : </h2>
        </div>
        {% if not object_list %}
          <div class="alert alert-warning">Il n'y a pas de produits correspondant à {{title|title}}</div>
        {% endif %}
        {% for product in object_list %}
          <div class="col-12 col-lg-4">
            <div class="product-thumb">
              <div class="nutriscore nutriscore-{{product.nutritional_score|upper}} text-center"></div>
                <a href="{% url target product.id %}">
                  <img src="{{product.img_url}}" class="rounded mx-auto d-block" alt="">
                </a>
                <div class="product-thumb-legend">
                  <p class="text-center">{{product|title}}</p>
                </div>
            </div>
          </div>
        {% endfor %}
        {% if is_paginated %}
          <div class="pagination">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">Précédente</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}">Suivante</a>
                  {% endif %}
              </span>
          </div>
        {% endif %}
      </div>
    </div>
</section>

{% endblock body %}

purbeurre/homepage/templates/homepage/home.html
{% extends "base.html" %}

{% load static %}

{% block body %}
  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
        {% if messages %}
          {% for message in messages%}
            <div class="alert alert-{{ message.tags }}">
              {{ message }} 
            </div>
          {% endfor %}
        {% endif %}
        
          <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <h2 class="text-white-75 font-weight-light mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
          <form class="navbar-form navbar-search" role="search" action="{% url 'aliments_off:search' %}" method="get">
                <div class="input-group">
                    <input name="query" class="form-control" type="text" placeholder="entrez votre produit !">
                  <div class="input-group-btn">
                      <button type="submit" class="btn btn-search btn-info">
                          <span class="glyphicon glyphicon-search"></span>
                          <span class="label-icon">Chercher</span>
                      </button>
                  </div>
                </div>
          </form>
        </div>
      </div>
    </div>
  </header>

  <!-- About Section -->
  <section class="page-section" id="about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-black mt-0">Colette et Remy</h2>
          <hr class="divider my-4">
          <h3 class="text-black mt-0">De la ratatouille aux croissants</h2>
          <p class="text-black-50 mb-4">Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille. </p>
          <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-12 order-1">
                  <p class="text-black-50 mb-4 text-justify"><strong>Colette Tatou</strong> : "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</p>
                </div>
                <div class="col-lg-6 col-12 order-3 order-lg-2">
                  <p class="text-black-50 mb-4 text-justify"><strong>Remy</strong> : "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
                </div>
                <div class="col-lg-6 col-12 order-2 order-lg-3">
                  <img src="{% static 'img/colette-tatou-full.png' %}" alt="Colette">
                </div>
                <div class="col-lg-6 col-12 order-4">
                  <img src="{% static 'img/ratatouille-portrait.jpg' %}" alt="Remy">
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section class="page-section bg-secondary" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="mt-0">Contactez-nous!</h2>
          <hr class="divider my-4">
          <p class="mb-5">Vous souhaitez partager votre avoir du bon gras avec nous, n'hésitez pas!</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center">
          <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
          <div>+1 (202) 555-0149</div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
          <!-- Make sure to change the email address in anchor text AND the link below! -->
          <a class="d-block" href="mailto:contact@yourwebsite.com">contact@yourwebsite.com</a>
        </div>
      </div>
    </div>
  </section>
{% endblock body %}

purbeurre/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Projet_08 OpenClassRoom">
  <meta name="author" content="Jessy Loppy">

  <title>Pur Beurre Le SITE</title>

  <!-- Font Awesome Icons -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="{% static 'css/creative.css' %}" rel="stylesheet">
  
  <!-- Other CSS -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  
  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="{% static 'img/logo_pur_beurre-favicon.png' %}"/>

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'homepage' %}">
        <img id="nav-brand-img" src="{% static "/img/logo_pur_beurre.png" %}" alt="Brand">
      Pur Beurre
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <form action="{% url 'aliments_off:search' %}" method="get">
              <input name="query" class="form-control form-control-sm" id="navbar-input" type="text" placeholder="Rechercher">
            </form>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'aliments_off:myproducts' %}"><i class="fas fa-carrot fa-2x"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'profile' %}"><i class="fas fa-user fa-2x"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt fa-2x"></i></a>
            </li>           
          {% else %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'register' %}">Register</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% block body %}

{% endblock body %} 

  <!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="text-center col-6"> <a href="{% url 'mentions' %}">Mentions légales</a></div>
        <div class="text-center col-6">Contact</div>
      </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static '/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static '/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static '/js/creative.min.js' %}"></script>

</body>

</html>

purbeurre/templates/base_title_section.html
  <!-- Title Section -->
  <header id="user-name" class="bg-user-name">
    <div class="container-fluid h-200">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <h1 class="text-white font-weight-bold">{{ title|title }}</h1>
      </div>
    </div>
</header>

purbeurre/users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body %}
{% include "base_title_section.html" with title="Connexion" %}
    <section class="">
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4"></legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Login</button>                
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Need an account ? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
                </small>
            </div>
        </div>
    </section>
{% endblock %}

purbeurre/users/templates/users/logout.html
{% extends "base.html" %}
{% block body %}
{% include "base_title_section.html" with title="Deconnecté" %}
    <div class="row h-10 align-items-center justify-content-center text-center">
        
        <h2></br><a href="{% url 'login' %}">LOG IN again</a></br></br></h2>

    
    </div>

{% endblock %}

purbeurre/users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body %}
{% include "base_title_section.html" with title=user.username %}
    <div class="row h-10 align-items-center justify-content-center text-center">
        
        <h2></br> {{ user.email }} </br></br></h2>

    </div>
{% endblock %}

purbeurre/users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body %}
{% include "base_title_section.html" with title="Enregistrement" %}
    <section class="">
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Sign Up</button>                
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already have an account ? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
                </small>
            </div>
        </div>
    </section>
{% endblock %}